CREATE DATABASE fshop;

CREATE TABLE `admin` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO admin(name,password)  ("admin","admin");

CREATE TABLE `cartegories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `slug` varchar(200) DEFAULT NULL,
  `parent_id` int(11) NOT NULL DEFAULT 0,
  `created_at` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=65 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO cartegories (id, name, slug, parent_id, created_at, updated_at) 
VALUES   
( 9, 'QUẦN', 'quan', 0, '2023-11-20 02:22:14', '2023-11-20 23:27:27'),
(10, 'ÁO', 'ao', 0, '2023-11-20 02:22:19', '2023-11-20 23:27:39'),
(13, 'Quần Jean', 'quan-jean', 9, '2023-11-20 02:54:57', '2023-11-20 03:18:51'),
(16, 'Áo Phông', 'ao-phong', 10, '2023-11-21 22:02:18', NULL),
(23, 'Quần Tây', 'quan-tay', 9, '2023-11-27 23:04:17', NULL),
(25, 'Áo Hoodie', 'ao-hoodie', 10, '2023-11-27 23:06:09', NULL),
(51, 'Áo Sơ Mi', 'ao-so-mi', 10, '2023-11-29 13:48:22', '2023-11-30 19:35:21'),
(63, 'Quần Short', 'quan-short', 9, '2023-11-30 22:00:05', NULL),
(64, 'Áo Sơ Mi Nam', 'ao-so-mi-nam', 10, '2023-12-04 01:25:32', NULL);

CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `price` double NOT NULL,
  `price_final` bigint(20) NOT NULL,
  `img` varchar(100) NOT NULL,
  `amount` bigint(20) NOT NULL,
  `cartegory_id` int(11) NOT NULL,
  `description` text DEFAULT NULL,
  `slug` varchar(100) DEFAULT NULL,
  `created_at` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `products_FK` (`cartegory_id`),
  CONSTRAINT `products_FK` FOREIGN KEY (`cartegory_id`) REFERENCES `cartegories` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `value` varchar(100) NOT NULL,
  `product_id` int(11) NOT NULL,
  `created_at` varchar(100) DEFAULT NULL,
  `updated_at` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `image_FK` (`product_id`),
  CONSTRAINT `image_FK` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `sizes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `weight` varchar(100) DEFAULT NULL,
  `height` varchar(100) DEFAULT NULL,
  `created_at` varchar(100) DEFAULT NULL,
  `updated_at` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `colors` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `created_at` varchar(100) DEFAULT NULL,
  `updated_at` varchar(100) DEFAULT NULL,
  `code_color` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_size` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `size_id` int(11) NOT NULL,
  `created_at` varchar(100) DEFAULT NULL,
  `updated_at` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_size_FK` (`product_id`),
  KEY `product_size_FK_1` (`size_id`),
  CONSTRAINT `product_size_FK` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `product_size_FK_1` FOREIGN KEY (`size_id`) REFERENCES `sizes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `product_color` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `color_id` int(11) NOT NULL,
  `created_at` varchar(100) DEFAULT NULL,
  `updated_at` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_color_FK_1` (`color_id`),
  KEY `product_color_FK` (`product_id`),
  CONSTRAINT `product_color_FK` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE,
  CONSTRAINT `product_color_FK_1` FOREIGN KEY (`color_id`) REFERENCES `colors` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `image_color` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image_id` int(11) NOT NULL,
  `color_id` int(11) NOT NULL,
  `created_at` varchar(100) DEFAULT NULL,
  `updated_at` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `image_color_FK` (`color_id`),
  KEY `Image_color_FK_1` (`image_id`),
  CONSTRAINT `Image_color_FK_1` FOREIGN KEY (`image_id`) REFERENCES `image` (`id`) ON DELETE CASCADE,
  CONSTRAINT `image_color_FK` FOREIGN KEY (`color_id`) REFERENCES `colors` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `provinces` (
  `code` varchar(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO provinces (code,name,full_name) VALUES(89,'An Giang','Tỉnh An Giang'),
(77,'Bà Rịa - Vũng Tàu','Tỉnh Bà Rịa - Vũng Tàu'),(24,'Bắc Giang','Tỉnh Bắc Giang'),
(06,'Bắc Kạn','Tỉnh Bắc Kạn'),(95,'Bạc Liêu','Tỉnh Bạc Liêu'),(27,'Bắc Ninh','Tỉnh Bắc Ninh'),
(83,'Bến Tre','Tỉnh Bến Tre'),(74,'Bình Dương','Tỉnh Bình Dương'),(52,'Bình Định','Tỉnh Bình Định'),
(70,'Bình Phước','Tỉnh Bình Phước'),(60,'Bình Thuận','Tỉnh Bình Thuận'),(96,'Cà Mau','Tỉnh Cà Mau'),
(92,'Cần Thơ','Thành phố Cần Thơ'),(04,'Cao Bằng','Tỉnh Cao Bằng'),(48,'Đà Nẵng','Thành phố Đà Nẵng'),
(66,'Đắk Lắk','Tỉnh Đắk Lắk'),(67,'Đắk Nông','Tỉnh Đắk Nông'),(11,'Điện Biên','Tỉnh Điện Biên'),
(75,'Đồng Nai','Tỉnh Đồng Nai'),(87,'Đồng Tháp','Tỉnh Đồng Tháp'),(64,'Gia Lai','Tỉnh Gia Lai'),
(02,'Hà Giang','Tỉnh Hà Giang'),(35,'Hà Nam','Tỉnh Hà Nam'),(01,'Hà Nội','Thành phố Hà Nội'),
(42,'Hà Tĩnh','Tỉnh Hà Tĩnh'),(30,'Hải Dương','Tỉnh Hải Dương'),(31,'Hải Phòng','Thành phố Hải Phòng'),
(93,'Hậu Giang','Tỉnh Hậu Giang'),(79,'Hồ Chí Minh','Thành phố Hồ Chí Minh'),(17,'Hoà Bình','Tỉnh Hoà Bình'),
(33,'Hưng Yên','Tỉnh Hưng Yên'),(56,'Khánh Hòa','Tỉnh Khánh Hòa'),(91,'Kiên Giang','Tỉnh Kiên Giang'),
(62,'Kon Tum','Tỉnh Kon Tum'),(12,'Lai Châu','Tỉnh Lai Châu'),(68,'Lâm Đồng','Tỉnh Lâm Đồng'),
(20,'Lạng Sơn','Tỉnh Lạng Sơn'),(10,'Lào Cai','Tỉnh Lào Cai'),(80,'Long An','Tỉnh Long An'),
(36,'Nam Định','Tỉnh Nam Định'),(40,'Nghệ An','Tỉnh Nghệ An'),(37,'Ninh Bình','Tỉnh Ninh Bình'),
(58,'Ninh Thuận','Tỉnh Ninh Thuận'),(25,'Phú Thọ','Tỉnh Phú Thọ'),(54,'Phú Yên','Tỉnh Phú Yên'),
(44,'Quảng Bình','Tỉnh Quảng Bình'),(49,'Quảng Nam','Tỉnh Quảng Nam'),(51,'Quảng Ngãi','Tỉnh Quảng Ngãi'),
(22,'Quảng Ninh','Tỉnh Quảng Ninh'),(45,'Quảng Trị','Tỉnh Quảng Trị'),(94,'Sóc Trăng','Tỉnh Sóc Trăng'),
(14,'Sơn La','Tỉnh Sơn La'),(72,'Tây Ninh','Tỉnh Tây Ninh'),(34,'Thái Bình','Tỉnh Thái Bình'),
(19,'Thái Nguyên','Tỉnh Thái Nguyên'),(38,'Thanh Hóa','Tỉnh Thanh Hóa'),(46,'Thừa Thiên Huế','Tỉnh Thừa Thiên Huế'),
(82,'Tiền Giang','Tỉnh Tiền Giang'),(84,'Trà Vinh','Tỉnh Trà Vinh'),(08,'Tuyên Quang','Tỉnh Tuyên Quang'),
(86,'Vĩnh Long','Tỉnh Vĩnh Long'),(26,'Vĩnh Phúc','Tỉnh Vĩnh Phúc'),(15,'Yên Bái','Tỉnh Yên Bái');


CREATE TABLE `districts` (
  `code` varchar(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `province_code` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`code`),
  KEY `idx_districts_province` (`province_code`),
  CONSTRAINT `districts_province_code_fkey` FOREIGN KEY (`province_code`) REFERENCES `provinces` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO districts (code,name,full_name) 
VALUES
(760,'1','Quận 1'),(771,'10','Quận 10'),(772,'11','Quận 11'),
(761,'12','Quận 12'),(770,'3','Quận 3'),(773,'4','Quận 4'),(774,'5','Quận 5'),(775,'6','Quận 6'),(778,'7','Quận 7'),
(776,'8','Quận 8'),(481,'A Lưới','Huyện A Lưới'),(908,'An Biên','Huyện An Biên'),(312,'An Dương','Huyện An Dương'),
(623,'An Khê','Thị xã An Khê'),(313,'An Lão','Huyện An Lão'),(542,'An Lão','Huyện An Lão'),(909,'An Minh','Huyện An Minh'),
(549,'An Nhơn','Thị xã An Nhơn'),(886,'An Phú','Huyện An Phú'),(329,'Ân Thi','Huyện Ân Thi'),(424,'Anh Sơn','Huyện Anh Sơn'),
(624,'Ayun Pa','Thị xã Ayun Pa'),(061,'Ba Bể','Huyện Ba Bể'),(202,'Ba Chẽ','Huyện Ba Chẽ'),(001,'Ba Đình','Quận Ba Đình'),
(458,'Ba Đồn','Thị xã Ba Đồn'),(748,'Bà Rịa','Thành phố Bà Rịa'),(386,'Bá Thước','Huyện Bá Thước'),(535,'Ba Tơ','Huyện Ba Tơ'),
(836,'Ba Tri','Huyện Ba Tri'),(271,'Ba Vì','Huyện Ba Vì'),(584,'Bác Ái','Huyện Bác Ái'),(596,'Bắc Bình','Huyện Bắc Bình'),
(213,'Bắc Giang','Thành phố Bắc Giang'),(085,'Bắc Hà','Huyện Bắc Hà'),(058,'Bắc Kạn','Thành phố Bắc Kạn'),
(954,'Bạc Liêu','Thành phố Bạc Liêu'),(031,'Bắc Mê','Huyện Bắc Mê'),(256,'Bắc Ninh','Thành phố Bắc Ninh'),
(034,'Bắc Quang','Huyện Bắc Quang'),(185,'Bắc Sơn','Huyện Bắc Sơn'),(726,'Bắc Tân Uyên','Huyện Bắc Tân Uyên'),
(515,'Bắc Trà My','Huyện Bắc Trà My'),(021,'Bắc Từ Liêm','Quận Bắc Từ Liêm'),(121,'Bắc Yên','Huyện Bắc Yên'),
(318,'Bạch Long Vĩ','Huyện Bạch Long Vĩ'),(063,'Bạch Thông','Huyện Bạch Thông'),(043,'Bảo Lạc','Huyện Bảo Lạc'),
(042,'Bảo Lâm','Huyện Bảo Lâm'),(680,'Bảo Lâm','Huyện Bảo Lâm'),(673,'Bảo Lộc','Thành phố Bảo Lộc'),
(086,'Bảo Thắng','Huyện Bảo Thắng'),(087,'Bảo Yên','Huyện Bảo Yên'),(082,'Bát Xát','Huyện Bát Xát'),
(719,'Bàu Bàng','Huyện Bàu Bàng'),(721,'Bến Cát','Thị xã Bến Cát'),(711,'Bến Cầu','Huyện Bến Cầu'),
(803,'Bến Lức','Huyện Bến Lức'),(829,'Bến Tre','Thành phố Bến Tre'),(731,'Biên Hòa','Thành phố Biên Hòa'),
(381,'Bỉm Sơn','Thị xã Bỉm Sơn'),(785,'Bình Chánh','Huyện Bình Chánh'),(835,'Bình Đại','Huyện Bình Đại'),
(181,'Bình Gia','Huyện Bình Gia'),(296,'Bình Giang','Huyện Bình Giang'),(198,'Bình Liêu','Huyện Bình Liêu'),
(690,'Bình Long','Thị xã Bình Long'),(352,'Bình Lục','Huyện Bình Lục'),(861,'Bình Minh','Thị xã Bình Minh'),
(524,'Bình Sơn','Huyện Bình Sơn'),(777,'Bình Tân','Quận Bình Tân'),(863,'Bình Tân','Huyện Bình Tân'),
(765,'Bình Thạnh','Quận Bình Thạnh'),(918,'Bình Thuỷ','Quận Bình Thuỷ'),(249,'Bình Xuyên','Huyện Bình Xuyên'),
(455,'Bố Trạch','Huyện Bố Trạch'),(696,'Bù Đăng','Huyện Bù Đăng'),(693,'Bù Đốp','Huyện Bù Đốp'),
(691,'Bù Gia Mập','Huyện Bù Gia Mập'),(647,'Buôn Đôn','Huyện Buôn Đôn'),(644,'Buôn Hồ','Thị xã Buôn Hồ'),
(643,'Buôn Ma Thuột','Thành phố Buôn Ma Thuột'),(964,'Cà Mau','Thành phố Cà Mau'),(819,'Cái Bè','Huyện Cái Bè'),
(817,'Cai Lậy','Thị xã Cai Lậy'),(820,'Cai Lậy','Huyện Cai Lậy'),(969,'Cái Nước','Huyện Cái Nước'),
(919,'Cái Răng','Quận Cái Răng'),(295,'Cẩm Giàng','Huyện Cẩm Giàng'),(235,'Cẩm Khê','Huyện Cẩm Khê'),
(570,'Cam Lâm','Huyện Cam Lâm'),(495,'Cẩm Lệ','Quận Cẩm Lệ'),(468,'Cam Lộ','Huyện Cam Lộ'),(739,'Cẩm Mỹ','Huyện Cẩm Mỹ'),
(195,'Cẩm Phả','Thành phố Cẩm Phả'),(569,'Cam Ranh','Thành phố Cam Ranh'),(390,'Cẩm Thủy','Huyện Cẩm Thủy'),
(446,'Cẩm Xuyên','Huyện Cẩm Xuyên'),(806,'Cần Đước','Huyện Cần Đước'),(787,'Cần Giờ','Huyện Cần Giờ'),
(807,'Cần Giuộc','Huyện Cần Giuộc'),(443,'Can Lộc','Huyện Can Lộc'),(844,'Càng Long','Huyện Càng Long'),
(040,'Cao Bằng','Thành phố Cao Bằng'),(866,'Cao Lãnh','Thành phố Cao Lãnh'),(873,'Cao Lãnh','Huyện Cao Lãnh'),
(183,'Cao Lộc','Huyện Cao Lộc'),(154,'Cao Phong','Huyện Cao Phong'),(317,'Cát Hải','Huyện Cát Hải'),
(683,'Cát Tiên','Huyện Cát Tiên'),(005,'Cầu Giấy','Quận Cầu Giấy'),(845,'Cầu Kè','Huyện Cầu Kè'),
(848,'Cầu Ngang','Huyện Cầu Ngang'),(884,'Châu Đốc','Thành phố Châu Đốc'),(750,'Châu Đức','Huyện Châu Đức'),
(889,'Châu Phú','Huyện Châu Phú'),(708,'Châu Thành','Huyện Châu Thành'),(808,'Châu Thành','Huyện Châu Thành'),
(821,'Châu Thành','Huyện Châu Thành'),(831,'Châu Thành','Huyện Châu Thành'),(847,'Châu Thành','Huyện Châu Thành'),
(877,'Châu Thành','Huyện Châu Thành'),(892,'Châu Thành','Huyện Châu Thành'),(905,'Châu Thành','Huyện Châu Thành'),
(933,'Châu Thành','Huyện Châu Thành'),(942,'Châu Thành','Huyện Châu Thành'),(932,'Châu Thành A','Huyện Châu Thành A'),
(187,'Chi Lăng','Huyện Chi Lăng'),(290,'Chí Linh','Thành phố Chí Linh'),(073,'Chiêm Hóa','Huyện Chiêm Hóa'),
(064,'Chợ Đồn','Huyện Chợ Đồn'),(822,'Chợ Gạo','Huyện Chợ Gạo'),(832,'Chợ Lách','Huyện Chợ Lách'),(065,'Chợ Mới','Huyện Chợ Mới'),
(893,'Chợ Mới','Huyện Chợ Mới'),(697,'Chơn Thành','Thị xã Chơn Thành'),(627,'Chư Păh','Huyện Chư Păh'),
(632,'Chư Prông','Huyện Chư Prông'),(639,'Chư Pưh','Huyện Chư Pưh'),(633,'Chư Sê','Huyện Chư Sê'),(277,'Chương Mỹ','Huyện Chương Mỹ'),
(925,'Cờ Đỏ','Huyện Cờ Đỏ'),(207,'Cô Tô','Huyện Cô Tô'),(471,'Cồn Cỏ','Huyện Cồn Cỏ'),(422,'Con Cuông','Huyện Con Cuông'),
(755,'Côn Đảo','Huyện Côn Đảo'),(783,'Củ Chi','Huyện Củ Chi'),(662,'Cư Jút','Huyện Cư Jút'),(657,'Cư Kuin','Huyện Cư Kuin'),
(945,'Cù Lao Dung','Huyện Cù Lao Dung'),(648,'Cư M'gar','Huyện Cư M'gar'),(413,'Cửa Lò','Thị xã Cửa Lò'),(720,'Dầu Tiếng','Huyện Dầu Tiếng'),
(724,'Dĩ An','Thành phố Dĩ An'),(679,'Di Linh','Huyện Di Linh'),(425,'Diễn Châu','Huyện Diễn Châu'),(574,'Diên Khánh','Huyện Diên Khánh'),
(309,'Dương Kinh','Quận Dương Kinh'),(707,'Dương Minh Châu','Huyện Dương Minh Châu'),(349,'Duy Tiên','Thị xã Duy Tiên'),
(508,'Duy Xuyên','Huyện Duy Xuyên'),(850,'Duyên Hải','Huyện Duyên Hải'),(851,'Duyên Hải','Thị xã Duyên Hải'),(150,'Đà Bắc','Huyện Đà Bắc'),
(681,'Đạ Huoai','Huyện Đạ Huoai'),(467,'Đa Krông','Huyện Đa Krông'),(672,'Đà Lạt','Thành phố Đà Lạt'),(682,'Đạ Tẻh','Huyện Đạ Tẻh'),
(506,'Đại Lộc','Huyện Đại Lộc'),(171,'Đại Từ','Huyện Đại Từ'),(626,'Đăk Đoa','Huyện Đăk Đoa'),(610,'Đắk Glei','Huyện Đắk Glei'),
(661,'Đăk Glong','Huyện Đăk Glong'),(615,'Đắk Hà','Huyện Đắk Hà'),(663,'Đắk Mil','Huyện Đắk Mil'),(634,'Đăk Pơ','Huyện Đăk Pơ'),
(666,'Đắk R'Lấp','Huyện Đắk R'Lấp'),(665,'Đắk Song','Huyện Đắk Song'),(612,'Đắk Tô','Huyện Đắk Tô'),(970,'Đầm Dơi','Huyện Đầm Dơi'),
(200,'Đầm Hà','Huyện Đầm Hà'),(674,'Đam Rông','Huyện Đam Rông'),(273,'Đan Phượng','Huyện Đan Phượng'),(753,'Đất Đỏ','Huyện Đất Đỏ'),
(507,'Điện Bàn','Thị xã Điện Bàn'),(100,'Điện Biên','Huyện Điện Biên'),(101,'Điện Biên Đông','Huyện Điện Biên Đông'),
(094,'Điện Biên Phủ','Thành phố Điện Biên Phủ'),(167,'Định Hóa','Huyện Định Hóa'),(189,'Đình Lập','Huyện Đình Lập'),
(736,'Định Quán','Huyện Định Quán'),(427,'Đô Lương','Huyện Đô Lương'),(308,'Đồ Sơn','Quận Đồ Sơn'),(230,'Đoan Hùng','Huyện Đoan Hùng'),
(677,'Đơn Dương','Huyện Đơn Dương'),(017,'Đông Anh','Huyện Đông Anh'),(006,'Đống Đa','Quận Đống Đa'),(505,'Đông Giang','Huyện Đông Giang'),
(461,'Đông Hà','Thành phố Đông Hà'),(960,'Đông Hải','Huyện Đông Hải'),(564,'Đông Hòa','Thị xã Đông Hòa'),(450,'Đồng Hới','Thành phố Đồng Hới'),
(340,'Đông Hưng','Huyện Đông Hưng'),(169,'Đồng Hỷ','Huyện Đồng Hỷ'),(695,'Đồng Phú','Huyện Đồng Phú'),(405,'Đông Sơn','Huyện Đông Sơn'),
(205,'Đông Triều','Thị xã Đông Triều'),(026,'Đồng Văn','Huyện Đồng Văn'),(689,'Đồng Xoài','Thành phố Đồng Xoài'),(558,'Đồng Xuân','Huyện Đồng Xuân'),
(631,'Đức Cơ','Huyện Đức Cơ'),(802,'Đức Hòa','Huyện Đức Hòa'),(801,'Đức Huệ','Huyện Đức Huệ'),(600,'Đức Linh','Huyện Đức Linh'),
(534,'Đức Phổ','Thị xã Đức Phổ'),(440,'Đức Thọ','Huyện Đức Thọ'),(678,'Đức Trọng','Huyện Đức Trọng'),(645,'Ea H'leo','Huyện Ea H'leo'),
(651,'Ea Kar','Huyện Ea Kar'),(646,'Ea Súp','Huyện Ea Súp'),(263,'Gia Bình','Huyện Gia Bình'),(018,'Gia Lâm','Huyện Gia Lâm'),(
297,'Gia Lộc','Huyện Gia Lộc'),(660,'Gia Nghĩa','Thành phố Gia Nghĩa'),(959,'Giá Rai','Thị xã Giá Rai'),(373,'Gia Viễn','Huyện Gia Viễn'),
(914,'Giang Thành','Huyện Giang Thành'),(365,'Giao Thủy','Huyện Giao Thủy'),(466,'Gio Linh','Huyện Gio Linh'),(906,'Giồng Riềng','Huyện Giồng Riềng'),
(834,'Giồng Trôm','Huyện Giồng Trôm'),(816,'Gò Công','Thị xã Gò Công'),(824,'Gò Công Đông','Huyện Gò Công Đông'),(823,'Gò Công Tây','Huyện Gò Công Tây'),
(710,'Gò Dầu','Huyện Gò Dầu'),(907,'Gò Quao','Huyện Gò Quao'),(764,'Gò Vấp','Quận Gò Vấp'),(268,'Hà Đông','Quận Hà Đông'),(024,'Hà Giang','Thành phố Hà Giang'),
(231,'Hạ Hoà','Huyện Hạ Hoà'),(048,'Hạ Lang','Huyện Hạ Lang'),(193,'Hạ Long','Thành phố Hạ Long'),(045,'Hà Quảng','Huyện Hà Quảng'),
(900,'Hà Tiên','Thành phố Hà Tiên'),(436,'Hà Tĩnh','Thành phố Hà Tĩnh'),(392,'Hà Trung','Huyện Hà Trung'),(306,'Hải An','Quận Hải An'),
(007,'Hai Bà Trưng','Quận Hai Bà Trưng'),(492,'Hải Châu','Quận Hải Châu'),(288,'Hải Dương','Thành phố Hải Dương'),(201,'Hải Hà','Huyện Hải Hà'),
(366,'Hải Hậu','Huyện Hải Hậu'),(470,'Hải Lăng','Huyện Hải Lăng'),(601,'Hàm Tân','Huyện Hàm Tân'),(597,'Hàm Thuận Bắc','Huyện Hàm Thuận Bắc'),
(598,'Hàm Thuận Nam','Huyện Hàm Thuận Nam'),(074,'Hàm Yên','Huyện Hàm Yên'),(400,'Hậu Lộc','Huyện Hậu Lộc'),(512,'Hiệp Đức','Huyện Hiệp Đức'),
(223,'Hiệp Hòa','Huyện Hiệp Hòa'),(051,'Hoà An','Huyện Hoà An'),(148,'Hòa Bình','Thành phố Hòa Bình'),(961,'Hoà Bình','Huyện Hoà Bình'),
(374,'Hoa Lư','Huyện Hoa Lư'),(709,'Hòa Thành','Thị xã Hòa Thành'),(497,'Hòa Vang','Huyện Hòa Vang'),(544,'Hoài Ân','Huyện Hoài Ân'),
(274,'Hoài Đức','Huyện Hoài Đức'),(543,'Hoài Nhơn','Thị xã Hoài Nhơn'),(002,'Hoàn Kiếm','Quận Hoàn Kiếm'),(399,'Hoằng Hóa','Huyện Hoằng Hóa'),
(008,'Hoàng Mai','Quận Hoàng Mai'),(432,'Hoàng Mai','Thị xã Hoàng Mai'),(498,'Hoàng Sa','Huyện Hoàng Sa'),(032,'Hoàng Su Phì','Huyện Hoàng Su Phì'),
(784,'Hóc Môn','Huyện Hóc Môn'),(503,'Hội An','Thành phố Hội An'),(903,'Hòn Đất','Huyện Hòn Đất'),(694,'Hớn Quản','Huyện Hớn Quản'),
(303,'Hồng Bàng','Quận Hồng Bàng'),(956,'Hồng Dân','Huyện Hồng Dân'),(437,'Hồng Lĩnh','Thị xã Hồng Lĩnh'),(868,'Hồng Ngự','Thành phố Hồng Ngự'),
(870,'Hồng Ngự','Huyện Hồng Ngự'),(474,'Huế','Thành phố Huế'),(339,'Hưng Hà','Huyện Hưng Hà'),(431,'Hưng Nguyên','Huyện Hưng Nguyên'),
(323,'Hưng Yên','Thành phố Hưng Yên'),(465,'Hướng Hóa','Huyện Hướng Hóa'),(444,'Hương Khê','Huyện Hương Khê'),(439,'Hương Sơn','Huyện Hương Sơn'),
(479,'Hương Thủy','Thị xã Hương Thủy'),(480,'Hương Trà','Thị xã Hương Trà'),(186,'Hữu Lũng','Huyện Hữu Lũng'),(628,'Ia Grai','Huyện Ia Grai'),
(618,'Ia H' Drai','Huyện Ia H' Drai'),(635,'Ia Pa','Huyện Ia Pa'),(625,'KBang','Huyện KBang'),(943,'Kế Sách','Huyện Kế Sách'),(575,'Khánh Sơn','Huyện Khánh Sơn'),
(573,'Khánh Vĩnh','Huyện Khánh Vĩnh'),(330,'Khoái Châu','Huyện Khoái Châu'),(307,'Kiến An','Quận Kiến An'),(912,'Kiên Hải','Huyện Kiên Hải'),
(902,'Kiên Lương','Huyện Kiên Lương'),(314,'Kiến Thuỵ','Huyện Kiến Thuỵ'),(795,'Kiến Tường','Thị xã Kiến Tường'),(343,'Kiến Xương','Huyện Kiến Xương'),
(350,'Kim Bảng','Huyện Kim Bảng'),(153,'Kim Bôi','Huyện Kim Bôi'),(331,'Kim Động','Huyện Kim Động'),(376,'Kim Sơn','Huyện Kim Sơn'),
(293,'Kim Thành','Huyện Kim Thành'),(292,'Kinh Môn','Thị xã Kinh Môn'),(613,'Kon Plông','Huyện Kon Plông'),(614,'Kon Rẫy','Huyện Kon Rẫy'),
(608,'Kon Tum','Thành phố Kon Tum'),(630,'Kông Chro','Huyện Kông Chro'),(655,'Krông A Na','Huyện Krông A Na'),(653,'Krông Bông','Huyện Krông Bông'),
(649,'Krông Búk','Huyện Krông Búk'),(650,'Krông Năng','Huyện Krông Năng'),(664,'Krông Nô','Huyện Krông Nô'),(637,'Krông Pa','Huyện Krông Pa'),
(654,'Krông Pắc','Huyện Krông Pắc'),(447,'Kỳ Anh','Huyện Kỳ Anh'),(449,'Kỳ Anh','Thị xã Kỳ Anh'),(417,'Kỳ Sơn','Huyện Kỳ Sơn'),(594,'La Gi','Thị xã La Gi'),
(675,'Lạc Dương','Huyện Lạc Dương'),(157,'Lạc Sơn','Huyện Lạc Sơn'),(159,'Lạc Thủy','Huyện Lạc Thủy'),(105,'Lai Châu','Thành phố Lai Châu'),
(876,'Lai Vung','Huyện Lai Vung'),(656,'Lắk','Huyện Lắk'),(071,'Lâm Bình','Huyện Lâm Bình'),(676,'Lâm Hà','Huyện Lâm Hà'),(237,'Lâm Thao','Huyện Lâm Thao'),
(388,'Lang Chánh','Huyện Lang Chánh'),(217,'Lạng Giang','Huyện Lạng Giang'),(178,'Lạng Sơn','Thành phố Lạng Sơn'),(080,'Lào Cai','Thành phố Lào Cai'),
(246,'Lập Thạch','Huyện Lập Thạch'),(875,'Lấp Vò','Huyện Lấp Vò'),(305,'Lê Chân','Quận Lê Chân'),(457,'Lệ Thủy','Huyện Lệ Thủy'),
(490,'Liên Chiểu','Quận Liên Chiểu'),(188,'Lộc Bình','Huyện Lộc Bình'),(448,'Lộc Hà','Huyện Lộc Hà'),(692,'Lộc Ninh','Huyện Lộc Ninh'),
(004,'Long Biên','Quận Long Biên'),(752,'Long Điền','Huyện Long Điền'),(857,'Long Hồ','Huyện Long Hồ'),(732,'Long Khánh','Thành phố Long Khánh'),
(936,'Long Mỹ','Huyện Long Mỹ'),(937,'Long Mỹ','Thị xã Long Mỹ'),(946,'Long Phú','Huyện Long Phú'),(740,'Long Thành','Huyện Long Thành'),
(883,'Long Xuyên','Thành phố Long Xuyên'),(218,'Lục Nam','Huyện Lục Nam'),(219,'Lục Ngạn','Huyện Lục Ngạn'),(135,'Lục Yên','Huyện Lục Yên'),
(152,'Lương Sơn','Huyện Lương Sơn'),(264,'Lương Tài','Huyện Lương Tài'),(353,'Lý Nhân','Huyện Lý Nhân'),(536,'Lý Sơn','Huyện Lý Sơn'),
(652,'M'Đrắk','Huyện M'Đrắk'),(156,'Mai Châu','Huyện Mai Châu'),(125,'Mai Sơn','Huyện Mai Sơn'),(858,'Mang Thít','Huyện Mang Thít'),
(629,'Mang Yang','Huyện Mang Yang'),(250,'Mê Linh','Huyện Mê Linh'),(027,'Mèo Vạc','Huyện Mèo Vạc'),(452,'Minh Hóa','Huyện Minh Hóa'),
(531,'Minh Long','Huyện Minh Long'),(838,'Mỏ Cày Bắc','Huyện Mỏ Cày Bắc'),(833,'Mỏ Cày Nam','Huyện Mỏ Cày Nam'),(533,'Mộ Đức','Huyện Mộ Đức'),
(123,'Mộc Châu','Huyện Mộc Châu'),(798,'Mộc Hóa','Huyện Mộc Hóa'),(194,'Móng Cái','Thành phố Móng Cái'),(137,'Mù Căng Chải','Huyện Mù Căng Chải'),
(102,'Mường Ảng','Huyện Mường Ảng'),(097,'Mường Chà','Huyện Mường Chà'),(083,'Mường Khương','Huyện Mường Khương'),(120,'Mường La','Huyện Mường La'),
(384,'Mường Lát','Huyện Mường Lát'),(095,'Mường Lay','Thị xã Mường Lay'),(096,'Mường Nhé','Huyện Mường Nhé'),(107,'Mường Tè','Huyện Mường Tè'),
(282,'Mỹ Đức','Huyện Mỹ Đức'),(328,'Mỹ Hào','Thị xã Mỹ Hào'),(358,'Mỹ Lộc','Huyện Mỹ Lộc'),(815,'Mỹ Tho','Thành phố Mỹ Tho'),(944,'Mỹ Tú','Huyện Mỹ Tú'),
(947,'Mỹ Xuyên','Huyện Mỹ Xuyên'),(072,'Na Hang','Huyện Na Hang'),(066,'Na Rì','Huyện Na Rì'),(971,'Năm Căn','Huyện Năm Căn'),(430,'Nam Đàn','Huyện Nam Đàn'),
(356,'Nam Định','Thành phố Nam Định'),(483,'Nam Đông','Huyện Nam Đông'),(510,'Nam Giang','Huyện Nam Giang'),(112,'Nậm Nhùn','Huyện Nậm Nhùn'),
(103,'Nậm Pồ','Huyện Nậm Pồ'),(291,'Nam Sách','Huyện Nam Sách'),(516,'Nam Trà My','Huyện Nam Trà My'),(362,'Nam Trực','Huyện Nam Trực'),
(019,'Nam Từ Liêm','Quận Nam Từ Liêm'),(931,'Ngã Bảy','Thành phố Ngã Bảy'),(948,'Ngã Năm','Thị xã Ngã Năm'),(401,'Nga Sơn','Huyện Nga Sơn'),
(062,'Ngân Sơn','Huyện Ngân Sơn'),(429,'Nghi Lộc','Huyện Nghi Lộc'),(407,'Nghi Sơn','Thị xã Nghi Sơn'),(442,'Nghi Xuân','Huyện Nghi Xuân'),
(419,'Nghĩa Đàn','Huyện Nghĩa Đàn'),(532,'Nghĩa Hành','Huyện Nghĩa Hành'),(361,'Nghĩa Hưng','Huyện Nghĩa Hưng'),(133,'Nghĩa Lộ','Thị xã Nghĩa Lộ'),
(304,'Ngô Quyền','Quận Ngô Quyền'),(973,'Ngọc Hiển','Huyện Ngọc Hiển'),(611,'Ngọc Hồi','Huyện Ngọc Hồi'),(389,'Ngọc Lặc','Huyện Ngọc Lặc'),
(494,'Ngũ Hành Sơn','Quận Ngũ Hành Sơn'),(052,'Nguyên Bình','Huyện Nguyên Bình'),(786,'Nhà Bè','Huyện Nhà Bè'),(568,'Nha Trang','Thành phố Nha Trang'),
(372,'Nho Quan','Huyện Nho Quan'),(742,'Nhơn Trạch','Huyện Nhơn Trạch'),(403,'Như Thanh','Huyện Như Thanh'),(402,'Như Xuân','Huyện Như Xuân'),
(369,'Ninh Bình','Thành phố Ninh Bình'),(299,'Ninh Giang','Huyện Ninh Giang'),(586,'Ninh Hải','Huyện Ninh Hải'),(572,'Ninh Hòa','Thị xã Ninh Hòa'),
(916,'Ninh Kiều','Quận Ninh Kiều'),(587,'Ninh Phước','Huyện Ninh Phước'),(585,'Ninh Sơn','Huyện Ninh Sơn'),(404,'Nông Cống','Huyện Nông Cống'),
(519,'Nông Sơn','Huyện Nông Sơn'),(517,'Núi Thành','Huyện Núi Thành'),(917,'Ô Môn','Quận Ô Môn'),(060,'Pác Nặm','Huyện Pác Nặm'),
(582,'Phan Rang-Tháp Chàm','Thành phố Phan Rang-Tháp Chàm'),(593,'Phan Thiết','Thành phố Phan Thiết'),(172,'Phổ Yên','Thành phố Phổ Yên'),
(476,'Phong Điền','Huyện Phong Điền'),(926,'Phong Điền','Huyện Phong Điền'),(109,'Phong Thổ','Huyện Phong Thổ'),(173,'Phú Bình','Huyện Phú Bình'),
(548,'Phù Cát','Huyện Phù Cát'),(333,'Phù Cừ','Huyện Phù Cừ'),(722,'Phú Giáo','Huyện Phú Giáo'),(563,'Phú Hoà','Huyện Phú Hoà'),
(482,'Phú Lộc','Huyện Phú Lộc'),(168,'Phú Lương','Huyện Phú Lương'),(347,'Phủ Lý','Thành phố Phủ Lý'),(545,'Phù Mỹ','Huyện Phù Mỹ'),
(754,'Phú Mỹ','Thị xã Phú Mỹ'),(768,'Phú Nhuận','Quận Phú Nhuận'),(233,'Phù Ninh','Huyện Phù Ninh'),(518,'Phú Ninh','Huyện Phú Ninh'),
(602,'Phú Quí','Huyện Phú Quí'),(911,'Phú Quốc','Thành phố Phú Quốc'),(698,'Phú Riềng','Huyện Phú Riềng'),(888,'Phú Tân','Huyện Phú Tân'),
(972,'Phú Tân','Huyện Phú Tân'),(638,'Phú Thiện','Huyện Phú Thiện'),(228,'Phú Thọ','Thị xã Phú Thọ'),(478,'Phú Vang','Huyện Phú Vang'),
(280,'Phú Xuyên','Huyện Phú Xuyên'),(122,'Phù Yên','Huyện Phù Yên'),(272,'Phúc Thọ','Huyện Phúc Thọ'),(244,'Phúc Yên','Thành phố Phúc Yên'),
(934,'Phụng Hiệp','Huyện Phụng Hiệp'),(688,'Phước Long','Thị xã Phước Long'),(957,'Phước Long','Huyện Phước Long'),(511,'Phước Sơn','Huyện Phước Sơn'),
(622,'Pleiku','Thành phố Pleiku'),(029,'Quản Bạ','Huyện Quản Bạ'),(385,'Quan Hóa','Huyện Quan Hóa'),(387,'Quan Sơn','Huyện Quan Sơn'),
(035,'Quang Bình','Huyện Quang Bình'),(477,'Quảng Điền','Huyện Quảng Điền'),(049,'Quảng Hòa','Huyện Quảng Hòa'),(522,'Quảng Ngãi','Thành phố Quảng Ngãi'),
(456,'Quảng Ninh','Huyện Quảng Ninh'),(454,'Quảng Trạch','Huyện Quảng Trạch'),(462,'Quảng Trị','Thị xã Quảng Trị'),(406,'Quảng Xương','Huyện Quảng Xương'),
(206,'Quảng Yên','Thị xã Quảng Yên'),(415,'Quế Phong','Huyện Quế Phong'),(509,'Quế Sơn','Huyện Quế Sơn'),(259,'Quế Võ','Thị xã Quế Võ'),
(275,'Quốc Oai','Huyện Quốc Oai'),(416,'Quỳ Châu','Huyện Quỳ Châu'),(420,'Quỳ Hợp','Huyện Quỳ Hợp'),(540,'Quy Nhơn','Thành phố Quy Nhơn'),
(421,'Quỳnh Lưu','Huyện Quỳnh Lưu'),(118,'Quỳnh Nhai','Huyện Quỳnh Nhai'),(338,'Quỳnh Phụ','Huyện Quỳnh Phụ'),(899,'Rạch Giá','Thành phố Rạch Giá'),
(867,'Sa Đéc','Thành phố Sa Đéc'),(088,'Sa Pa','Thị xã Sa Pa'),(616,'Sa Thầy','Huyện Sa Thầy'),(382,'Sầm Sơn','Thành phố Sầm Sơn'),
(084,'Si Ma Cai','Huyện Si Ma Cai'),(108,'Sìn Hồ','Huyện Sìn Hồ'),(016,'Sóc Sơn','Huyện Sóc Sơn'),(941,'Sóc Trăng','Thành phố Sóc Trăng'),
(076,'Sơn Dương','Huyện Sơn Dương'),(220,'Sơn Động','Huyện Sơn Động'),(529,'Sơn Hà','Huyện Sơn Hà'),(560,'Sơn Hòa','Huyện Sơn Hòa'),
(116,'Sơn La','Thành phố Sơn La'),(269,'Sơn Tây','Thị xã Sơn Tây'),(530,'Sơn Tây','Huyện Sơn Tây'),(527,'Sơn Tịnh','Huyện Sơn Tịnh'),
(493,'Sơn Trà','Quận Sơn Trà'),(557,'Sông Cầu','Thị xã Sông Cầu'),(165,'Sông Công','Thành phố Sông Công'),(561,'Sông Hinh','Huyện Sông Hinh'),
(253,'Sông Lô','Huyện Sông Lô'),(126,'Sông Mã','Huyện Sông Mã'),(127,'Sốp Cộp','Huyện Sốp Cộp'),(860,'Tam Bình','Huyện Tam Bình'),
(247,'Tam Dương','Huyện Tam Dương'),(248,'Tam Đảo','Huyện Tam Đảo'),(370,'Tam Điệp','Thành phố Tam Điệp'),(106,'Tam Đường','Huyện Tam Đường'),
(502,'Tam Kỳ','Thành phố Tam Kỳ'),(236,'Tam Nông','Huyện Tam Nông'),(871,'Tam Nông','Huyện Tam Nông'),(794,'Tân An','Thành phố Tân An'),
(705,'Tân Biên','Huyện Tân Biên'),(766,'Tân Bình','Quận Tân Bình'),(706,'Tân Châu','Huyện Tân Châu'),(887,'Tân Châu','Thị xã Tân Châu'),
(904,'Tân Hiệp','Huyện Tân Hiệp'),(869,'Tân Hồng','Huyện Tân Hồng'),(796,'Tân Hưng','Huyện Tân Hưng'),(423,'Tân Kỳ','Huyện Tân Kỳ'),
(155,'Tân Lạc','Huyện Tân Lạc'),(734,'Tân Phú','Huyện Tân Phú'),(767,'Tân Phú','Quận Tân Phú'),(825,'Tân Phú Đông','Huyện Tân Phú Đông'),
(818,'Tân Phước','Huyện Tân Phước'),(240,'Tân Sơn','Huyện Tân Sơn'),(799,'Tân Thạnh','Huyện Tân Thạnh'),(805,'Tân Trụ','Huyện Tân Trụ'),
(111,'Tân Uyên','Huyện Tân Uyên'),(723,'Tân Uyên','Thành phố Tân Uyên'),(216,'Tân Yên','Huyện Tân Yên'),(599,'Tánh Linh','Huyện Tánh Linh'),
(504,'Tây Giang','Huyện Tây Giang'),(003,'Tây Hồ','Quận Tây Hồ'),(562,'Tây Hoà','Huyện Tây Hoà'),(703,'Tây Ninh','Thành phố Tây Ninh'),
(547,'Tây Sơn','Huyện Tây Sơn'),(053,'Thạch An','Huyện Thạch An'),(445,'Thạch Hà','Huyện Thạch Hà'),(391,'Thạch Thành','Huyện Thạch Thành'),
(276,'Thạch Thất','Huyện Thạch Thất'),(336,'Thái Bình','Thành phố Thái Bình'),(414,'Thái Hoà','Thị xã Thái Hoà'),(164,'Thái Nguyên','Thành phố Thái Nguyên'),
(341,'Thái Thụy','Huyện Thái Thụy'),(110,'Than Uyên','Huyện Than Uyên'),(513,'Thăng Bình','Huyện Thăng Bình'),(232,'Thanh Ba','Huyện Thanh Ba'),
(874,'Thanh Bình','Huyện Thanh Bình'),(428,'Thanh Chương','Huyện Thanh Chương'),(294,'Thanh Hà','Huyện Thanh Hà'),(380,'Thanh Hóa','Thành phố Thanh Hóa'),
(800,'Thạnh Hóa','Huyện Thạnh Hóa'),(491,'Thanh Khê','Quận Thanh Khê'),(351,'Thanh Liêm','Huyện Thanh Liêm'),(300,'Thanh Miện','Huyện Thanh Miện'),
(278,'Thanh Oai','Huyện Thanh Oai'),(837,'Thạnh Phú','Huyện Thạnh Phú'),(238,'Thanh Sơn','Huyện Thanh Sơn'),(239,'Thanh Thuỷ','Huyện Thanh Thuỷ'),
(020,'Thanh Trì','Huyện Thanh Trì'),(949,'Thạnh Trị','Huyện Thạnh Trị'),(009,'Thanh Xuân','Quận Thanh Xuân'),(872,'Tháp Mười','Huyện Tháp Mười'),
(398,'Thiệu Hóa','Huyện Thiệu Hóa'),(395,'Thọ Xuân','Huyện Thọ Xuân'),(894,'Thoại Sơn','Huyện Thoại Sơn'),(967,'Thới Bình','Huyện Thới Bình'),
(927,'Thới Lai','Huyện Thới Lai'),(738,'Thống Nhất','Huyện Thống Nhất'),(923,'Thốt Nốt','Quận Thốt Nốt'),(718,'Thủ Dầu Một','Thành phố Thủ Dầu Một'),
(769,'Thủ Đức','Thành phố Thủ Đức'),(804,'Thủ Thừa','Huyện Thủ Thừa'),(725,'Thuận An','Thành phố Thuận An'),(588,'Thuận Bắc','Huyện Thuận Bắc'),
(119,'Thuận Châu','Huyện Thuận Châu'),(589,'Thuận Nam','Huyện Thuận Nam'),(262,'Thuận Thành','Thị xã Thuận Thành'),(279,'Thường Tín','Huyện Thường Tín'),
(396,'Thường Xuân','Huyện Thường Xuân'),(311,'Thuỷ Nguyên','Huyện Thuỷ Nguyên'),(260,'Tiên Du','Huyện Tiên Du'),(342,'Tiền Hải','Huyện Tiền Hải'),
(315,'Tiên Lãng','Huyện Tiên Lãng'),(332,'Tiên Lữ','Huyện Tiên Lữ'),(514,'Tiên Phước','Huyện Tiên Phước'),(199,'Tiên Yên','Huyện Tiên Yên'),
(846,'Tiểu Cần','Huyện Tiểu Cần'),(890,'Tịnh Biên','Thị xã Tịnh Biên'),(525,'Trà Bồng','Huyện Trà Bồng'),(849,'Trà Cú','Huyện Trà Cú'),
(862,'Trà Ôn','Huyện Trà Ôn'),(842,'Trà Vinh','Thành phố Trà Vinh'),(139,'Trạm Tấu','Huyện Trạm Tấu'),(951,'Trần Đề','Huyện Trần Đề'),
(968,'Trần Văn Thời','Huyện Trần Văn Thời'),(138,'Trấn Yên','Huyện Trấn Yên'),(712,'Trảng Bàng','Thị xã Trảng Bàng'),(737,'Trảng Bom','Huyện Trảng Bom'),
(180,'Tràng Định','Huyện Tràng Định'),(891,'Tri Tôn','Huyện Tri Tôn'),(469,'Triệu Phong','Huyện Triệu Phong'),(397,'Triệu Sơn','Huyện Triệu Sơn'),
(363,'Trực Ninh','Huyện Trực Ninh'),(047,'Trùng Khánh','Huyện Trùng Khánh'),(576,'Trường Sa','Huyện Trường Sa'),(298,'Tứ Kỳ','Huyện Tứ Kỳ'),
(617,'Tu Mơ Rông','Huyện Tu Mơ Rông'),(528,'Tư Nghĩa','Huyện Tư Nghĩa'),(261,'Từ Sơn','Thành phố Từ Sơn'),(098,'Tủa Chùa','Huyện Tủa Chùa'),
(099,'Tuần Giáo','Huyện Tuần Giáo'),(418,'Tương Dương','Huyện Tương Dương'),(559,'Tuy An','Huyện Tuy An'),(667,'Tuy Đức','Huyện Tuy Đức'),
(555,'Tuy Hoà','Thành phố Tuy Hoà'),(595,'Tuy Phong','Huyện Tuy Phong'),(550,'Tuy Phước','Huyện Tuy Phước'),(453,'Tuyên Hóa','Huyện Tuyên Hóa'),
(070,'Tuyên Quang','Thành phố Tuyên Quang'),(966,'U Minh','Huyện U Minh'),(913,'U Minh Thượng','Huyện U Minh Thượng'),(281,'Ứng Hòa','Huyện Ứng Hòa'),
(196,'Uông Bí','Thành phố Uông Bí'),(089,'Văn Bàn','Huyện Văn Bàn'),(551,'Vân Canh','Huyện Vân Canh'),(140,'Văn Chấn','Huyện Văn Chấn'),
(203,'Vân Đồn','Huyện Vân Đồn'),(326,'Văn Giang','Huyện Văn Giang'),(128,'Vân Hồ','Huyện Vân Hồ'),(325,'Văn Lâm','Huyện Văn Lâm')
,(182,'Văn Lãng','Huyện Văn Lãng'),(571,'Vạn Ninh','Huyện Vạn Ninh'),(184,'Văn Quan','Huyện Văn Quan'),(136,'Văn Yên','Huyện Văn Yên'),
(930,'Vị Thanh','Thành phố Vị Thanh'),(935,'Vị Thuỷ','Huyện Vị Thuỷ'),(030,'Vị Xuyên','Huyện Vị Xuyên'),(227,'Việt Trì','Thành phố Việt Trì'),
(222,'Việt Yên','Huyện Việt Yên'),(412,'Vinh','Thành phố Vinh'),(316,'Vĩnh Bảo','Huyện Vĩnh Bảo'),(950,'Vĩnh Châu','Thị xã Vĩnh Châu'),
(735,'Vĩnh Cửu','Huyện Vĩnh Cửu'),(797,'Vĩnh Hưng','Huyện Vĩnh Hưng'),(464,'Vĩnh Linh','Huyện Vĩnh Linh'),(393,'Vĩnh Lộc','Huyện Vĩnh Lộc'),
(958,'Vĩnh Lợi','Huyện Vĩnh Lợi'),(855,'Vĩnh Long','Thành phố Vĩnh Long'),(546,'Vĩnh Thạnh','Huyện Vĩnh Thạnh'),(924,'Vĩnh Thạnh','Huyện Vĩnh Thạnh'),
(910,'Vĩnh Thuận','Huyện Vĩnh Thuận'),(252,'Vĩnh Tường','Huyện Vĩnh Tường'),(243,'Vĩnh Yên','Thành phố Vĩnh Yên'),(170,'Võ Nhai','Huyện Võ Nhai'),
(359,'Vụ Bản','Huyện Vụ Bản'),(441,'Vũ Quang','Huyện Vũ Quang'),(344,'Vũ Thư','Huyện Vũ Thư'),(859,'Vũng Liêm','Huyện Vũng Liêm'),
(747,'Vũng Tàu','Thành phố Vũng Tàu'),(033,'Xín Mần','Huyện Xín Mần'),(741,'Xuân Lộc','Huyện Xuân Lộc'),(364,'Xuân Trường','Huyện Xuân Trường'),
(751,'Xuyên Mộc','Huyện Xuyên Mộc'),(360,'Ý Yên','Huyện Ý Yên'),(132,'Yên Bái','Thành phố Yên Bái'),(141,'Yên Bình','Huyện Yên Bình'),
(124,'Yên Châu','Huyện Yên Châu'),(221,'Yên Dũng','Huyện Yên Dũng'),(394,'Yên Định','Huyện Yên Định'),(375,'Yên Khánh','Huyện Yên Khánh'),
(251,'Yên Lạc','Huyện Yên Lạc'),(234,'Yên Lập','Huyện Yên Lập'),(028,'Yên Minh','Huyện Yên Minh'),(377,'Yên Mô','Huyện Yên Mô'),(327,'Yên Mỹ','Huyện Yên Mỹ'),
(258,'Yên Phong','Huyện Yên Phong'),(075,'Yên Sơn','Huyện Yên Sơn'),(426,'Yên Thành','Huyện Yên Thành'),(215,'Yên Thế','Huyện Yên Thế'),
(158,'Yên Thủy','Huyện Yên Thủy');

CREATE TABLE `wards` (
  `code` varchar(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `district_code` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`code`),
  KEY `idx_wards_district` (`district_code`),
  CONSTRAINT `wards_district_code_fkey` FOREIGN KEY (`district_code`) REFERENCES `districts` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- NẾU MUỐN THÊM XÃ/THỊ TRẤN CHO CƠ SỞ DỮ LIỆU -> wards.sql

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `remember_token` varchar(100) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `created_at` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `token` varchar(100) DEFAULT NULL,
  `province_id` varchar(20) DEFAULT NULL,
  `district_id` varchar(20) DEFAULT NULL,
  `ward_id` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  KEY `users_FK` (`ward_id`),
  KEY `users_FK_1` (`province_id`),
  KEY `users_FK_2` (`district_id`),
  CONSTRAINT `users_FK` FOREIGN KEY (`ward_id`) REFERENCES `wards` (`code`),
  CONSTRAINT `users_FK_1` FOREIGN KEY (`province_id`) REFERENCES `provinces` (`code`),
  CONSTRAINT `users_FK_2` FOREIGN KEY (`district_id`) REFERENCES `districts` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `orders` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `address` varchar(255) NOT NULL,
  `created_at` varchar(255) DEFAULT NULL,
  `updated_at` varchar(255) DEFAULT NULL,
  `state` tinyint(4) DEFAULT NULL,
  `total` double NOT NULL,
  PRIMARY KEY (`id`),
  KEY `orders_FK` (`user_id`),
  CONSTRAINT `orders_FK` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `details_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `amount` int(11) NOT NULL,
  `price` double NOT NULL,
  PRIMARY KEY (`id`),
  KEY `details_order_FK` (`order_id`),
  KEY `details_order_FK_1` (`product_id`),
  CONSTRAINT `details_order_FK` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
  CONSTRAINT `details_order_FK_1` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;